### ISSUE TITLE
Loss of customisable functionality on timer application

### ISSUE THREAD

**Issue by therealnatasha** [hayatoito/hayatoito.github.io#1]
I have been using your excellent timer for around 18 months.  I prefer it to most others on the web because it is 1) very simple and 2) the time periods are customisable. 
 
I note however since your upgrade that the customisable code no longer works – you can only use it in increments of 25 minutes.  Is there any way I can still access the customisable bit?  I am a researcher and 25 minutes is just too short for a time period.

**Comment by hayatoito** [comment]
Sorry for the trouble and thank you for letting me know that.
I have been rewriting the timer. Some features which existed in the previous version are not implemented yet in the new version.

I've just supported `t` parameter again.  e.g. http://hayato.io/timer/?t=120,10,120,30
Could you confirm it? If it does not meet your expectations, please let me know that.

**Comment by therealnatasha** [comment]
That seems to work Hayato.  Thanks very much.

ありがとうございました
