### ISSUE TITLE
[Typo] 継続的インゲグレーション -> 継続的インテグレーション in https://hayato.io/2017/making-web/

### ISSUE THREAD

**Issue by thara** [hayatoito/hayatoito.github.io#15]
Found typo the following.

> ビルド・継続的インゲグレーションテスト

shoule be

> ビルド・継続的インテグレーションテスト

at https://github.com/hayatoito/hayatoito.github.io/blob/master/2017/making-web/index.html#L373

**Comment by hayatoito** [comment]
Fixed. Thanks!
