### ISSUE TITLE
Complexity measure may be wrong in "Chrome におけるノードツリーの実装"

### ISSUE THREAD

**Issue by Yatima-Kagurazaka** [hayatoito/hayatoito.github.io#19]
I think
https://github.com/hayatoito/hayatoito.github.io/blob/5d1b4701021b3d6e30ec60fd1d56cc0d89e0f265/2017/dom/index.html#L148
>合計すると各ノードには 5 つ ( `parent`, `firstChild`, `lastChild`, `previous`, `next`) のポインタがあります。
このツリーの表現により Web で標準で利用できる多くの DOM API は定数時間 O(1) で実装が可能です。

shoud be
`定数時間 O(N)`.

You also said
>Siblings are stored as a linked list. It takes O(N) to access a parent's n-th child.
Parent can't tell how many children it has in O(1).

at [README](https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/core/dom/README.md) on `Source/core/dom`.

**Comment by hayatoito** [comment]
Thank you for the feedback, however, I WONTFIX this. *O(1)* here is not a mistake.

You might want to try "課題: 1" to figure out how the given DOM APIs, `ParentNode.append(node)`, `ChildNode.before(node)`, or `ChildNode.remove()`, can be implemented in *O(1)*, with a given tree's representation.

**Comment by Yatima-Kagurazaka** [comment]
Thanks for your advice!
I know, I misunderstood the context! haha
