### ISSUE TITLE
Add createdCallback (v0) -> constructor (v1) to "What's new in Shadow DOM v1"

### ISSUE THREAD

**Issue by JanMiksovsky** [hayatoito/hayatoito.github.io#2]
I didn't see mention of this significant change.

**Comment by JanMiksovsky** [comment]
Ah, I see that you're focusing the document exclusively on Shadow DOM, not Custom Elements. Never mind, then.

**Comment by hayatoito** [comment]
Yeah, that is only for Shadow DOM. :) Closing.
