### ISSUE TITLE
Link url to WebKit dir in chromium repository is 404 not found

### ISSUE THREAD

**Issue by shoken0x** [hayatoito/hayatoito.github.io#23]
Example: 
https://github.com/hayatoito/hayatoito.github.io/blob/92fa2ba7e490eff251f876e3133fe20eabdb84c4/2017/dom/index.html#L75

I think URL changed `https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/core/dom/README.md` to  `https://chromium.googlesource.com/chromium/src/+/refs/heads/master/third_party/blink/renderer/core/dom/README.md` .

This article is great and will be read by many people in the future, so I think it would be good to have a note.

**Comment by hayatoito** [comment]
Thanks! Fixed at https://github.com/hayatoito/hayatoito.github.io/commit/253b5f1396c74faaddfb06cd4e591878b607eeb7.
