### ISSUE TITLE
カギカッコが抜けています

### ISSUE THREAD

**Issue by DENRYO** [hayatoito/hayatoito.github.io#32]
素晴らしい記事の公開ありがとうございます

＞理論編
次に理論編です。先程の結論で示した方針を実行するのは簡単そうに聞こえます。ですが、この世の中にはその妨げになる「情報」がたくさんあふれています。

「いま、株価は史上最高値です！ PER は過去最高です！暴落は 2 年以内におとずれるでしょう！」
「暴落はまだ始まったばかりです。これから株価はもっと下げます。全部、現金にしましょう！」
「インデックス投資なんて大して儲かりませんよ！短期間で大儲けするなら、FX です！！

のFXです！！のあとの　’」’　がなかったため、報告いたします
（すごく細かいことなのですが、素晴らしい記事だからこそこのような細かい部分が少し気になってしまうと考え、ご容赦ください）

以上です。よろしくお願いいたします。

**Comment by hayatoito** [comment]
ありがとうございます。修正しました。https://github.com/hayatoito/hayatoito.github.io/commit/0a3d5f2e428316c9d4df9d54a61d828523d9653f
