### ISSUE TITLE
(typo)どうして時価総額加重平均にもどづく

### ISSUE THREAD

**Issue by ysdyt** [hayatoito/hayatoito.github.io#33]
小さな点ですが、
https://hayatoito.github.io/2020/investing/#a-11
のタイトルにtypoがありましたのでご報告です。
とても参考になる素晴らしい記事の公開ありがとうございます！

**Comment by hayatoito** [comment]
ありがとうございます。修正しました。 https://github.com/hayatoito/hayatoito.github.io/commit/ceceb1a9a94618a4ba9e9bfc47eb362befab0fff
