### ISSUE TITLE
リターンの分布の数式

### ISSUE THREAD

**Issue by HT1028** [hayatoito/hayatoito.github.io#36]
大変貴重な情報の共有、誠に有り難うございます。

内容を拝見しながらリターンの分布図を手許（エクセル）で作成することを試みたのですが、どうも上手くいきません。（具体的には、2年目以降の標準偏差や中央値（こちらは”EXP（μ）”と理解しております）の求め方に悩んでおります）

差し支えなければ、具体的な計算式を何等かの形でご共有頂くことは可能でしょうか。

お手数をお掛け致しますが、何卒ご検討の程、宜しくお願い申し上げます。

**Comment by hayatoito** [comment]
ご質問ありがとうございます。

このサイトのまとめがわかりやすいかと思います。
http://www.fund-no-umi.com/blog/2009/08/27-bc8a.html

記事でのリターンの分布等も同じ式で計算しています。

**Comment by HT1028** [comment]
早速のご返信、誠に有り難うございます。
ご教授頂きましたサイトの内容も拝見しながら、理解を深めて参りたく存じます。
