### ISSUE TITLE
投資の指針について

### ISSUE THREAD

**Issue by jiro-123** [hayatoito/hayatoito.github.io#37]
有益な情報ありがとうございます。
今でこそつみたてNISAの普及によりインデックスファンドによる資産形成が王道になっていますが、hayatoito様が市場ポートフォリオが最も効率が良いと確信し、投資の指針として実践しようと考えたきっかけみたいな話がありましたら是非聞いてみたいです。リーマンショックのときは評価額が大きく落ち込んだと思いますが、hayatoito様は最初にリスク許容度を考慮したアセットアロケーションを設定しているので、やはり暴落時でも自身の投資の軸がぶれることなかったのでしょうか？当時は市場ポートフォリオを投資指針にしている方は少数派だったと思います。正直継続できるのはすごいと思います。私はつみたてNISA始めたばかりの初心者なので、暴落時の心構えなどありましたら何かお聞きできたらうれしいです。

**Comment by hayatoito** [comment]
ご質問ありがとうございます。筆者個人に関しての質問は申し訳ないのですけど、Closeさせてください。すいません。できましたら一般的な質問でお願いできますでしょうか？ よろしくお願いします :)
