### ISSUE TITLE
[質問] 株価は長期的には右肩上がりだという前提について

### ISSUE THREAD

**Issue by kinosuke01** [hayatoito/hayatoito.github.io#39]
こんにちは。はじめまして。
少し気になった点があったので質問させてください。

> 株価はランダムウォークしながらも長期的には右肩上がりだという前提にたちます。

とありましたが、そもそもこの前提は正しいのでしょうか？

**Comment by hayatoito** [comment]
資本主義である限り株価は上昇する方向に向かうそうですよ。 :)

あと、そもそも株式のようにリスクのあるものにはリスクプレミアムという対価・リターンがあるというのが基本的な考え方のようですね。リターンがないと誰もリスクをとらないので。

**Comment by kinosuke01** [comment]
「資本主義である限り上昇する方向に向かう」というのが、
調べても何故そうなのかよく分からなかったのですが、
実績として、これまでずっと上がり続けているというのは分かりました。
200年スパンのグラフ見たら、これからも上がり続けると思っちゃいますね。

返信ありがとうございました :)
