### ISSUE TITLE
Node.rootNode is now resolved

### ISSUE THREAD

**Issue by diddledan** [hayatoito/hayatoito.github.io#4]
It seems the issue mentioned in [line 715 thru 722 of 2016/shadowdomv1/index.html](https://github.com/hayatoito/hayatoito.github.io/blob/master/2016/shadowdomv1/index.html#L715) regarding the disagreement of name for `Node.rootNode` is now resolved in favour of a function called `Node.getRootNode()`. The page needs updating to reflect the new consensus.

**Comment by hayatoito** [comment]
Thank you for feedback! I have updated the page.
