### ISSUE TITLE
TODO情報について

### ISSUE THREAD

**Issue by hidexir** [hayatoito/hayatoito.github.io#40]
いきなり失礼します。以下の情報がきになったのでissueあげさせていただきます。

2017/faq
```txt
Scala から Rust に変えてよかったところは何ですか？ 
TODO: 書きます。 (-> draft/faq.md)
Go は使用しないのですか？
TODO: 書きます。 (-> draft/faq.md)
```

**Comment by hayatoito** [comment]
ありがとうございます。今のところ、特に追記する予定はありませんので、WONTFIXとさせてください。
2017/faq もとりあえずそのままで。ごめんなさい。

せっかくご質問いただいたので、ここでちょっとだけお答えしておくと、Scala も Go も他に理由がない限りはあえて使用しようとは全く思いません。
