### ISSUE TITLE
リターンとリスクについて

### ISSUE THREAD

**Issue by yusukeyamauchi** [hayatoito/hayatoito.github.io#41]
素晴らしい記事ありがとうございます。一点のみ気になる点があります。リスク資産100%で、最悪のケースで50%になるとするなら、-3∂のとき-55%になるように、期待リターン5%に対してリスク20%くらいかと思いますが、記事の表ではリスクが10%になっています。全世界株式インデックスファンドのリスクリターンも概ねその程度かと思いますが、いかがでしょうか。
参照： J.P.モルガンの超長期市場予測

**Comment by hayatoito** [comment]
ありがとうございます。このあたり、記事ではそれほど明確に書いていないせいか、誤解されやすいポイントな気がしますね。

意図としては、「現実の全世界株式インデックスファンドのリスクリターン」はこうですと、記事中で明記するのを避けたいというのがあります。ここでの「リスク・リターン」はあくまで

> ここでは仮にリスク資産のリターンを 5%、リスクを 10%としています。

と記事中にあるように、あくまで「仮の数字」です。各自が自分で選んだ商品のリスク・リターンを自分で調べる・仮定する・その数字で記事中の数字を置き換えることを期待しています。

**Comment by yusukeyamauchi** [comment]
確かに実際に購入する時期や、金利の情勢などによって期待リターンなど揺れ動くので、こういった考え方を伝える記事ではリスクリターンは示さない方がいいのですね。納得致しました。
