### ISSUE TITLE
保有期間とリスクについて

### ISSUE THREAD

**Issue by aohigedes** [hayatoito/hayatoito.github.io#42]
株式市場が右肩上がりであれは期待値は常に正なので、例え明日に現金が必要になるとしても許容リスクである限り投資したほうが得というのは理解できます。
ですが、実際には日々の値動きがあるため、運用期間が短いほどリスクが高くなり、運用期間が長いほどリスクが低くなる前提に立つと、許容リスクも運用期間に応じて検討したくなるのですが、どのように考えたら良いのでしょうか？

**Comment by hayatoito** [comment]
個人のリスク許容度に関しての質問にはあまり答えたくありません...。申し訳ないですがご理解を。

一般的には「n年後にx%に失うことを許容できるとした場合、1年後には何%まで失うことができるか？」は、
解くのが簡単ではない数学の問題になると思います。
