### ISSUE TITLE
「普通の人が資産運用で99点をとる方法とその考え方」の転載許可について

### ISSUE THREAD

**Issue by jun801** [hayatoito/hayatoito.github.io#45]
はやといと　様

初めまして。jun801と申します。
標記の件について、御確認よろしくお願い致します。

最近日本のSNS上において、資産運用を行う際に適切と思えないような商品を初心者に勧める情報や分かりにくい情報が多い印象を受けていました。
そんな中、本人のリスク許容度において時価総額加重平均インデックスを買い続けるという普通の人が99点をとる方法（ポートフォリオ理論として当たり前なのですが）をより分かりやすく手にすることができました。実際に私もその理論の重要性を理解することができ現在も実践中です。私はよい記事はより多くの人に見られてこそ意味があると思っています。ですので、宜しければ記事の転載許可をはやといと様から得たいと思っています。
大変お忙しい中と思いますが、御確認お願いいたします。

GitHub Issuesの使い方があっているのか分かりませんが連絡があなたへいっていることを願います。それでは。

**Comment by hayatoito** [comment]
引用はもちろんOKですが、転載については考えたことがなかったです。

転載を許可する予定は今のところありません。具体的にどのような媒体への転載をお考えなのでしょうか？

**Comment by jun801** [comment]
返信ありがとうございます。

転載という表現は適切でありませんでした。正しくは引用でした。

具体的な媒体は、Twitterです。自分の実践と主張の補完のために引用させていただきたいと思います。
私が想定していたのは、「文字数の関係で自分の主張が書けない場合に転載と類似したものになるのではないか」ということです。勿論、次のつぶやきに自分の主張をしたいと考えています。

**Comment by hayatoito** [comment]
引用はもちろんOKですよ。引用元を明記する等、正しい引用であり限り、私に許可をとる必要はありません 😄 。

**Comment by jun801** [comment]
念のため一言伝えておきたかったのです。ありがとうございました。
