### ISSUE TITLE
アセットアロケーションの見直しについて

### ISSUE THREAD

**Issue by statistics910** [hayatoito/hayatoito.github.io#46]
はじめまして。資産運用の初心者ですが、この記事にはとても納得感がありました。ありがとうございます。読んでいて少しわからなかった部分がありましたので可能であれば質問させてください。
1.アセットアロケーションの見直しについて
アセットアロケーションの定期的な見直しが必要である理解しました。仮に現金：リスク資産＝500万：500万で運用を始め、リスク資産が200万減った場合にはリスク資産を100万購入し、現金：リスク資産＝400万：400万とする理解であってますでしょうか。

2.アセットアロケーションの見直しタイミングについて
アセットアロケーションの見直しは1年または数年に1度と言うお話でしたが、もう少し短期（半年に1回や1ヶ月に1回）とした場合に問題はありますでしょうか。初心者はそんなに高頻度でやる必要ないよということでしょうか。

**Comment by takuaraki** [comment]
投資信託でS&P500を運用しています。私の理解で良ければ参考にしてください。

①アセットアロケーションの見直しについて
アセットアロケーションの見直しタイミングで、リスク許容度が変わらずかつ総資産が800万円の場合は400万：400万で合っていると思います。

※ リスク資産の最大損失が（記事にあったように）-50%のまま変わらないという前提も置いています

②アセットアロケーションの見直しタイミングについて
結論として、記事の資産運用の方針を取る「普通の人」なら1ヶ月に1回やる必要はないと思います。

理由は、見直しする必要があるくらい理想と現実のアセットアロケーションのズレが生じるには1ヶ月は短すぎるからです。

--- 以下は理由の詳細です。長いので読まなくてもいいです ---
理想と現実のズレが出てくるのは以下の2つの場合だと思います。
・現実のアセットアロケーションが変化した
・理想のアセットアロケーションが変化した

理想の変化についてはライフステージの変化によるものと考えられるので定期的な見直しとは関係ないと判断して考慮から外して、現実のアセットアロケーションの変化を考えます。

以下の例を考えてみます。
・総資産 500万円
・理想のアセットアロケーション 1：1 → 現実のアセットアロケーション 250万：250万
・毎月の貯金額5万円
・臨時収入や出費は定期的な見直しとは関係ないので考えない

毎月の貯金額が5万円なので次の月の現実のアセットアロケーションは255万：250万、つまり1.02：1となります。これは理想のアセットアロケーションの1：1と比べて大きくずれていないように見えます。なので、1ヶ月でアセットアロケーションを見直す意味はあまりなさそうです。では、1年後だとどうでしょうか。1年後には5*12=60万円の貯金ができるので現実のアセットアロケーションは310万：250万となります。この場合は1.24：1なので、ちょっとズレてきたなと考えて現金を投資信託に回すということはありそうです。なので、この例では1年に1度見直すというのは妥当に思えます。1.24：1でもいいかなと思う人は3年後にするかもしれません。

※ 毎月全額貯金するという例を書きましたが、一部を投資信託に積み立てればもっと見直しのスパンを長くすることができます。たとえば、上記の例で2.5万円を貯金にして2.5万円を投資信託に積み立てたとすれば、急な収入や出費がない限り一生ズレの修正をする必要はありません。
※ もちろん、現在の総資産や毎月の貯金額によってもズレ方は変わってきます。たとえば、総資産が50万円だったら1ヶ月で30万：25万になるので、1.2：1となり1ヶ月でもちょっとズレます。ただ、総資産50万でリスク資産が25万だったら-50%で-12.5万円、逆に+50%では+12.5万円です。もし、見直しによって27.5万：27.5万にしていたら -13.75万、+13.75万円なので、1.25万円の差しかありません。要はその大きさの総資産額だとあまり見直す意味がないということです。また、上述の積立を使えば総資産50万円でも1ヶ月であまりズレることはないかと思います。
