### ISSUE TITLE
確定拠出年金の出口戦略について

### ISSUE THREAD

**Issue by yagiyagiyag** [hayatoito/hayatoito.github.io#47]
確定拠出年金も時価総額加重平均を採用したインデックスファンドをお勧めされていますが、その出口戦略について質問させてください。

特定口座に移管可能なNISAと異なりDCには明確な出口があると認識しています。受け取り直前に暴落する可能性があっても時価総額加重平均のインデックスファンドを続けるべきとお考えでしょうか？
その際、受け取り直前で暴落した場合はどのように対応するお考えでしょうか？
(60歳で受け取らず、受け取り期間を伸ばす方法があるかと思いますが、退職金控除を考えると得策には思えません。)

私としては、50歳頃から徐々に債権や定期預金型のものに切り替えた方が暴落のリスクを回避できるのでは？と考えています。

また、DCの受け取り方法(一括・年金)についてもご意見を聞かせてください。

**Comment by mono0926** [comment]
暴落中に受け取って、そのまますぐ同じインデックスファンドに投資、はどうですかね 🤔

**Comment by yagiyagiyag** [comment]
確かにそれが1番合理的ですね。
回答ありがとうございました。

この解説は本当にわかりやすくまとまっていて、今後考えがブレそうになった際に見返す羅針盤になりそうです。

**Comment by hayatoito** [comment]
> 受け取り直前に暴落する可能性があっても時価総額加重平均のインデックスファンドを続けるべきとお考えでしょうか？

記事中に十分に説明していると思います。
「一括投資直後に暴落したらどうしよう」という質問と基本的には同じだと思います。
