### ISSUE TITLE
質問：以下の部分で「リスク資産として株式だけでなく債券も入れたほうがよいといわれたのですが？」

### ISSUE THREAD

**Issue by baymax-hn** [hayatoito/hayatoito.github.io#48]
大変すばらしい記事をありがとうございます。わかりやすく、かつ明確です。また様々なポイントでの論拠を示していただいて、その論拠を見ることも非常にためになっています。

そのなかで、「リスク資産として株式だけでなく債券も入れたほうがよいといわれたのですが？」の説明で、”個人で複数のリスク資産を組み合わせてポートフォリオを工夫して組む必要性はありません。＊＊そんな時代はとっくに終わっています＊＊”（強調は私がつけてます）、”もともとそのためのインデックス投資であり投資信託です。最適なポートフォリオを個人でがんばって組む必要性があった＊＊時代はとっくに終わっています＊＊。”にある、”その時代はとっくに終わっている”と述べられている論拠は何になるのかぜひ教えていただけないでしょうか。

たしかに債券を含んで最適化するのが「普通の人」には難しいというのは了解しますし、また「近年の債券の低リターンはほとんど意味ない」などの話もまあそうかなと思うので、「債券は入れなくてもよい」という回答自体に異論はないです。それはそれとして、他の説明の部分では説得力＆論拠ある説明をずっとされているので、上の個所の「時代はとっくに終わっている」についても何か確かな理由があるのだろうと推測しているのですが、ぜひそれについても教えていただけたらと思っています。

どうぞよろしくお願いいたします。

--

**Comment by hayatoito** [comment]
ありがとうごじます。特に追加する予定はありません。
