### ISSUE TITLE
「株価の変動」が「対数正規分布」するのではなく、「期待リターン」の変動が「対数正規分布」するのではないでしょうか。

### ISSUE THREAD

**Issue by sutehachi** [hayatoito/hayatoito.github.io#51]
「これらのチャートは、株価の変動は対数正規分布だというモデルに基づいて描きました。」
とご説明されておりますが、正確には、「株価の変動」は正規分布であり、「期待リターン」が「対数正規分布」する
というのが正しいのではないかと思いますがいかがでしょうか。

μを表すものとしてとして提示されている式から、株価の変動を幾何ブラウン運動として
モデル化されていると思料されますが、その場合、初期項をS0, ある時点での株価をStとすると、
ln(St/S0)が正規分布するということになるかと思います。ここでSt/S0はある時点における期待リターンを
表しますので、対数正規分布の定義（確率変数Yの対数をとったものが正規分布するとき、Yは対数正規分布する。）
から、St/S0、すなわち「期待リターンが対数正規分布に従う」、という結論が導かれることになろうかと思います。

したがって、「これらのチャートは、株価の変動は対数正規分布だというモデルに基づいて描きました。」との記載は、
「これらのチャートは、期待リターンの変動は対数正規分布だというモデルに基づいて描きました。」等に修正されるほうが
よろしいかと思います。

**Comment by hayatoito** [comment]
ありがとうございます。とくに修正する予定はありません。
