### ISSUE TITLE
確定拠出年金の出口と退職所得控除について

### ISSUE THREAD

**Issue by chypot** [hayatoito/hayatoito.github.io#52]
25歳からidecoを35年間続けた場合、運用利回り5%だったとすると2487万3048円積みたたります。
一方で、退職する20年以内に転職または独立をしていた場合、退職所得控除は800万円です。
つまり 約 1687万円に対して退職時に所得税・住民税がかかってしまうということですよね。これでは結局税の繰延べにしかならないのではないでしょうか？

この文書ではNISAよりもidecoのお得度を高く紹介していますが、転職や独立の可能性がある人はある程度以上はidecoよりもNISAを優先すべきでしょうか？

**Comment by hayatoito** [comment]
記事中にも記載してあると思いますが、ideco のお得度は、人によって異なります。記事中ではそれについてあまり詳しく触れる予定はありません。
