### ISSUE TITLE
判断材料としての中央値と最頻値について

### ISSUE THREAD

**Issue by hajimemasitemar** [hayatoito/hayatoito.github.io#53]
興味深い記事をありがとうございます。
リターンとリスクの両方の影響を受けるのは中央値だけでなく最頻値についてもそうだと思われますが、投資判断の上ではどちらをより参考とするのが良いと思われますか。
例えば、リターン 5%, リスク 20% の場合におけるグラフでは、年数が経つに連れ中央値はプラス方向（プラスサム）に伸びますが最頻値で見るとマイナス方向（マイナスサム）に向かっています。この投資をどう考えるか。中央値と最頻値、どちらが重みを持つのか教えて頂ければ幸いです。

**Comment by hayatoito** [comment]
統計の一般的な話がそのまま当てはまると思います。

つまり最頻値はあまり当てになりません。
少し意地悪な言い方をすれば、最頻値をXだとすると最頻値になる確率はゼロです  😄   `P(x=X) = 0` です。
あくまで P(x>X) などで考える必要がありますね。中央値の場合は P(x>X) = 0.5 ですね。

**Comment by hajimemasitemar** [comment]
ご返答ありがとうございました。このような質問をさせていただいた理由は、ご存じかも知れませんが「ファンドの海」というサイトがあり、その中で最頻値と中央値のどちらが起こりやすいかについて議論がなされており（http://www.fund-no-umi.com/blog/2011/08/post-bab0.htmlのコメント欄）、そこではサイト主様の主張である最頻値で結論されていたのです。（ただ、中央値で判断すべきだという指摘は他欄でも数人の方からなされていました）

上下の確率半々、が最も起こりやすいという考え方ですね。大変参考になりました。
hayatoito様のご活躍をお祈り申し上げます。

**Comment by hayatoito** [comment]
ありがとうございます。最頻値で判断するのは明らかに不適切であり、間違った判断につながると思います 😄
