### ISSUE TITLE
資産運用について

### ISSUE THREAD

**Issue by rumba77** [hayatoito/hayatoito.github.io#54]
https://hayatoito.github.io/2020/investing/

こちらの記事を拝見したものです。
大変参考になりました。
一点質問があります。
もし可能であれば記事で取り上げていただけると幸いです。

相続や贈与などにより、個別株を手に入れた場合、一旦それらを売却したうえで、（リスク許容度の範囲で）インデックス投信を購入すべきでしょうか？
それとも、それらをそのままホールドすべきでしょうか？

　※質問の回答には関係ないのかもしれませんが、下記に情報を補記します。

　・個別株の銘柄は時価総額ランキングトップ10内
　・運用者は30歳
　・個別株は現在数%の含み益あり

**Comment by hayatoito** [comment]
乗り換えの是非を判断するには:

* 残りの運用年数
* 個別株の想定リターン、リスク
* インデックスの想定リターン、リスク
* 現在の含み益の割合

など妥当な仮定をもとに実際に計算してみる必要があると思います。

現在30歳、含み益が数%程度でしたら、ほとんどの妥当な仮定において、一旦売却、インデックス投信を購入するほうがお得になるという計算結果が得られると思いますよ。

これが、残りの運用年数10年、現在含み益50%等でしたら、間違いなくホールドだと思います。

実際はもちろん仮定によって結果がかわってきますので、私がここで言えるのはこの程度までだと思います。計算方法なども私からはここで示したりはしないです 😄

**Comment by rumba77** [comment]
個別にご返信をいただきありがとうございます！
感激しています。

記事の内容を参考に自分でも計算を試みようと思います。ご回答ありがとうございました。
