### ISSUE TITLE
NISAのリバランスについて

### ISSUE THREAD

**Issue by Rabbits0411** [hayatoito/hayatoito.github.io#55]
https://hayatoito.github.io/2020/investing/

こちらの記事を拝見いたしました。
大変参考になったのですが、1点質問があります。

つみたてNISAを利用している場合でもリバランスは行うべきなのでしょうか？
私は今年から利用を開始したのですが、投資信託が年利5%で増加すると仮定すると、いずれは現金の入金が追いつかずアセットアロケーションと乖離していくと思います。

その際、アセットアロケーションを優先して投資信託を売却するべきか、それとも非課税枠を活かすために乖離を受容すべきか、どちらがベターなのか疑問に思い、ご質問しました。

ご回答いただけますと幸いです。よろしくお願いいたします。

**Comment by hayatoito** [comment]
質問ありがとうございます。

一般には記事で一貫して主張しているようにリスク許容度とそれにあったアセットアロケーションを最優先させるべきだと思います。

> その際、アセットアロケーションを優先して投資信託を売却するべきか、それとも非課税枠を活かすために乖離を受容すべきか、どちらがベターなのか疑問に思い、ご質問しました。

後者を優先させるということは（わかりやすくするため仮の話ですが）逆にいうと

「非課税枠が仮に現在の40万円から増えた場合は、それを余らせることなく投資するべきだ！」

という結論になってしまいませんか？

つまり現在

A) 現金 80万円 : つみたてNISA 80万円

という自分のリスク許容度を踏まえたアセットアロケーションをとっている人が

「来年からつみたてNISAの枠が無制限になります！」という制度の変更があったからといってすぐに

B) 現金 0万円 : つみたてNISA 160万円

にしないですよね？

私は B にしません、Aのままですというのなら、それが結論になっていると思います。

現実に話を戻すと、もちろん、頻繁なリバランスはよくない、それがつみたてNISAの場合はなおさら、一度使用した枠は復活しないので余計に慎重にならないといけないという考慮点はあると思いますので、制度を活かすという点では、個人にとって最適なところは、先程の例でいうならばAとBの間のどこかになるとは思います。ですが記事の主張はあくまでリターンを優先させるのでなく、本人のリスク許容度にあったアセットアロケーションをとりましょうです。

ではでは。

**Comment by Juntanaa** [comment]
隼人様

こんにちは。

毎年の投入現金が上限に達しない場合、特定口座の株式を売却し新NISAへ移行すべきか？について御見解を伺いたいです。

想定される状況は、長期投資（15年以上）を前提に、2023年までに特定口座で購入していたVOOが約800万円あり、毎年の現金による購入金額は約100万円としている場合、特定口座の商品を売却して260万円を用意して、上限360万円まで購入した方がよいのでしょうか？それとも既存の特定口座はそのままにして、新NISA枠は100万円ずつ埋めていくべきなのでしょうか？
また、つみたて：120万円、一般：240万円となっていますが、前者をeMAXIS Slim 米国株式 (S&P500）等の投資信託を120万円積立てるとして、問題は後者です。一般の240万円についてはS＆P500相当のETFを購入するべきなのか、あるいは、外国税額控除がないことから前者と同じ投資信託を購入するべきなのか、どちらが合理的なのでしょうか？

一つ目の私の意見は、特定口座を売却してでも新NISA枠の360万円/年を埋めていくべきと考えます。なぜなら非課税期間の恒久化のメリットを最大限長期に生かすことができるからです。また、二つ目の私の意見は、一般についてはNISAに伴う二重課税にならないことからETFではなく投資信託を買うべきかと考えます。日本における外国ETFは外国税額控除を受けてこそ旨味があると認識しているからです。

私は公務員になった2018年からideco及びつみたてnisaでVTI投資を始めて、2020年から残りの現金をリスク範囲内でVOOを購入しています。隼人様の「普通の人が資産運用で 99 点をとる方法とその考え方」を見て、やはりこの方法が私にとってのbetterであると分かりました。どうか今後も堅実な資産運用をしていくためにお知恵を貸してください。
お時間があるときで構いませんので御返答よろしくお願いいたします。長文失礼いたしました。

　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　20230103 Juntana

**Comment by hayatoito** [comment]
記事を新NISA対応させました。

https://github.com/hayatoito/hayatoito.github.io/commit/24bf77e7814dd9b7b4046b9a3d24e0aac1b648ed

**Comment by Juntanaa** [comment]
計算結果まで丁寧にありがとうございました。
thank you!
