### ISSUE TITLE
投資信託と海外ETF比較のプログラム「計算結果 (in Rust)」について

### ISSUE THREAD

**Issue by shir0shiki** [hayatoito/hayatoito.github.io#56]
初めまして。

https://hayatoito.github.io/2020/investing/

上記の記事を拝見させていただきました。
大変参考になりました、ありがとうございます。

一点細かい点ですが、質問させていただきます。
投資信託と海外ETFのパフォーマンスをRustで比較した下記のプログラムについてです。
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1cb8936a2894dbdd28272794e73bbbbb

こちらの投資信託側のプログラムを拝見すると配当再投資型であるかと存じます。配当再投資の際に配当に10%課税（外国）、最後に利益に20%課税（国内）されていますが、2020年1月1日より開始された投資信託等の二重課税調整制度がプログラムに反映されていないように思いました。

結論には影響なく、この記事の趣旨には無関係と言っていい箇所だと思いますが気になったの質問させていただきます。

**Comment by hayatoito** [comment]
「二重課税調整制度」についてお知らせありがとうございました。

ちゃんと調査したわけではありませせんが、検索して少し見てみたところ
例)
https://faq.monex.co.jp/faq/show/5730?category_id=261

実際にお客様に分配金を支払う場合には二重課税調整制度が適用されると記載されていますが、
お客様に分配金を支払わないで内部で配当を再投資する際にも二重課税調整制度が適用されるかどうかについて明確な記述は発見できませんでした。

私はこれ以上深入りするするつもりはあまりありませんが（ごめんなさい）、
もしお客様に分配金を支払わないで内部で配当を再投資する（具体的には eMAXIS Slim 全世界株式 等です）タイプの投資信託にも適用されるという記載がどこかにあるのなら教えていただけると幸いです。

その際には、記事の該当箇所に追記します。

**Comment by shir0shiki** [comment]
早速返信いただき有難うございます。
確かにその辺りの明確な記述は私も見つけられませんでした、よく調べないで質問してしまい申し訳ありません。

どちらにせよそこまで労力をかけて気にする箇所ではないですね、有難うございました。

**Comment by hayatoito** [comment]
いえいえ。ありがとうございました。

おそらくですが二重課税調整はその名の通り「二重課税を防止する」のが目的であり、すでに外国で徴収されている外国税額を「国内の所得税から差し引く」という名目になっている以上、分配金を出さないで配当を再投資する場合は、差し引く先の国内の所得税がそもそもまだないため、そのタイミングでは指し引きのしようがない、調整するのは難しいのでしょうね。
