### ISSUE TITLE
仮想通貨について

### ISSUE THREAD

**Issue by mopeneko** [hayatoito/hayatoito.github.io#57]
時価総額加重平均型インデックスファンドに投資することが株式市場でシャープレシオを最大化することに繋がることには共感できました。

ただ、仮想通貨について特に言及することなく否定していることに疑問に感じています。

適切なアセットアロケーションを行うことで、ポートフォリオのシャープレシオを高めることに繋がるのではないでしょうか。

**Comment by mopeneko** [comment]
もちろん、シャープレシオのみの観点から投資先を語るべきではなく、リスクを評価する必要があると思っています。

特に仮想通貨は株式と比べ物にならないリスクがありますから、つみたてNISAをベースに株式や現金で老後資金を確保しつつ、それでも給料が余りそうなら投資するべきだと考えています。

**Comment by hayatoito** [comment]
ご質問ありがとうございます。

暗号通貨等については、記事中で具体的に触れるつもりはありません。

これは暗号通貨に限った話ではありません。

>怪しいもの・実績がないものに手をだす

> 例)

> 記事の公開にあたってこの部分は削除しました。具体的に書くと怒られそうなので ...察してください。

察してください。

「シャープレシオを高めるのではないか？」についてはここのQ&Aで回答していると思います。

> リスク資産として株式だけでなく債券も入れたほうがよいといわれたのですが？

この例では債券を例にしていますが、暗号通貨であろうと基本的には同じです。

例えば記事ではこの章でリスク許容度に応じた具体的にアセットアロケーションを提示しています。

https://hayatoito.github.io/2020/investing/#a-4

たとえばこの章を (現金、株式、暗号通貨) を用いて、試しに書き直すことは可能でしょうか？
それらがもとの (現金、株式) を組み合わせてアセットアロケーションをどのように上回るのか、具体的に客観的な理由をもって提示できますか？それらは記事に載せるに値しますか？

記事では普通の人が実行できる具体的なアセットアロケーションしか提示する予定はありません。あしからず。

**Comment by mopeneko** [comment]
なるほど、細かい回答ありがとうございます。

確かに、言われてみればこの記事はそもそも普通の人がそれなりのパフォーマンスを低コストで実現するためのものでしたね。

改めて記事を最初から最後まで飛ばさず読み返してみたのですが、この言葉が印象に残りました。

> この際、決して「市場平均よりよい成績をとってやろう」と「勝手な行動」をとらないでください。その瞬間、魔法がとけて、あなたはただの「普通の人」になってしまいます。ただの「普通の人」の投資判断が、長期で継続的に市場平均に勝てることはないでしょう。

そもそも暗号通貨が長期的に値上がりするのであれば、機関投資家が買っていますよね…
なぜ気づかなかったのか…

私は少し欲深かったのかもしれないです。

納得したので、IssueをCloseさせていただきます。

改めて、回答ありがとうございました。

**Comment by hayatoito** [comment]
いえいえ、ご質問ありがとうございました。

> 普通の人がそれなりのパフォーマンスを低コストで実現するためのものでしたね。

誤解があると思いますが、この記事は、それなりのパフォーマンスを低コストで実現するものではないですよ。
少なくとも著者にそのような意図はありません。

（それぞれのリスク許容度において）「もっとも高いパフォーマンスをとる」「99点を達成する」のを目的とした記事です。
