### ISSUE TITLE
(typo) うちほど

### ISSUE THREAD

**Issue by keigoi** [hayatoito/hayatoito.github.io#59]
「例:Bさんの場合」とのころに

> B さんは、現在 100 万円ある現金の**うちほど**、最低限残しておく部分は除いて、ほぼすべてを一括で投資しました。

https://hayatoito.github.io/2020/investing/#b

というtypoがありましたので報告します。
参考になる記事をありがとうございます😊

**Comment by hayatoito** [comment]
ありがとうございます。 修正しました。https://github.com/hayatoito/hayatoito.github.io/commit/9f2e5f12cb12990d2fc141fe73442a98064d392e.
