### ISSUE TITLE
Example of element using templates, slots and shadowDOM together

### ISSUE THREAD

**Issue by caraya** [hayatoito/hayatoito.github.io#6]
Hayato, 

Other than the example from the Webkit blog, do you know if there is an example of ShadowDOM that uses both templates and slots?

If there isn't one, would you consider creating it? :-)

**Comment by hayatoito** [comment]
Thank you for reaching me.  We have a good article [here](
https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom), which I have reviewed.

**Comment by caraya** [comment]
Thank you. The article itself didn't have what I was looking for but the link to the fancy-tabs example had something close to what I was looking for
