### ISSUE TITLE
99点資産運用

### ISSUE THREAD

**Issue by nascasca** [hayatoito/hayatoito.github.io#60]
99点資産運用の記事を拝見しました。たいへん興味深いものでしたので、いくつか質問させていただきたいです。

1 「株式が右肩上がりになる前提」とありますが、その根拠はなんでしょうか。この前提で見れば説明は正しいのですが、前提の正当性が説明されてないと思います。過去、数世紀にわたり上がってきたのは事実ですが、この理屈だと「田中さんはこれまで70年生きてきたから、これからも70年生きる」ことになります。「過去ずっと上がってきた」以外の説明があればお願いします。

2 マクロ経済では、株価は景気後退時には大きく下がります。景気後退の大きな定期サイクルがきている時は、リスク回避のために利確したほうがいいと思いますが、いかがでしょうか。普通の人向けの記事だからマクロ経済は対象外とのことでしたらいいですが、そうでない場合はお考えをお聞かせいただきたいです。

3 貨幣の購買力について、お考えをお聞かせください。仮に2の答えが「数年で戻るから」だとします。しかし未来には貨幣の購買力が変わっており、同じ額面で前と同じものが変えるわけではありません。株価とともに物価も上がってきているのがここ数十年の先進国です。記事にあるのは「額面」の話で、購買力、塩漬けにしていた期間の機会損失額を計算に含めていないと思いますが、ここはどうお考えでしょうか。

4 日銀の金融緩和政策が与える影響について、どうお考えでしょうか。

5 一時的に下がることでメンタルに支障をきたす人がいます。これらのメンタル損失リスクも、説明に加えたほうが親切ではないでしょうか。

以上、長々と書きましたが、ご回答いただけるとありがたいです。

**Comment by hayatoito** [comment]
質問ありがとうございます。 大変申し訳ないですが、記事の内容に関係ない質問が多いように思えます。

1. 記事中に参考文献としていくつかリンクを示していると思うのですが、それらはご覧になりましたか？この記事で主張していることは、筆者個人のオリジナルのアイデアではなく、広く世の中に知れ渡った理論をもとにしています。

2. 具体的な記事の訂正箇所等、最初に結論を示していただけると助かります。

そうではない、記事の内容とは関係のない質問であるなら、それらがどのように記事の結論に影響を与えるのか、質問の目的を最初にクリアにしていだけると助かります。

質問の目的を伝えるのが難しいのであれば、[ここでの回答](https://github.com/hayatoito/hayatoito.github.io/issues/57#issuecomment-1336373350
)などを参考に、まずは具体的な例があるとよいと思います。個々の質問にそれを含めることができるとよいと思います。

記事の内容に関係がない・結論に影響を与えない質問であれば、申し訳ないですが、
個別の質問に私がここで答える予定はありません...。

5 については具体的にどのようなものを考えていますか？ 具体的に [Pull Request ](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests)  をだしてくれると助かります。

いったん、Close します。
