### ISSUE TITLE
持株会奨励金の投資効率について

### ISSUE THREAD

**Issue by KENN4565** [hayatoito/hayatoito.github.io#63]
記事を拝見いたしました。
大変参考になりました。ありがとうございます。

個別株への投資はインデックスファンドへの投資に投資効率で劣るため、合理的な選択ではないという認識です。
その上で１点ご質問がございます。

個別株への投資に、持株会奨励金(一般的に10%程度)という下駄を履かせたとしても、
インデックスファンドへの投資に比べて投資効率で劣りますでしょうか。

素人考えでは、毎月限度額(5万程度)まで自社株を購入し、単元株分溜まったら、即売却し、インデックスファンドを購入する。
という運用で、ただインデックスファンドへの投資をするより高いリターンを得られそうに感じます。

もちろん、自社株のボラティリティ等で変わってくるかとは思いますが、
持株会奨励金制度を使用すべきかどうかの検討のために、ご意見をいただきたく存じます。

以上　ご回答いただけますと幸甚です。

**Comment by hayatoito** [comment]
どこかに損益分岐点はあるとおもいますが、ここで聞いても回答は得られないと思います。直感的には10%でるならやったほうがよいとは思いますが。
