### ISSUE TITLE
インデックス商品について

### ISSUE THREAD

**Issue by fujikzy** [hayatoito/hayatoito.github.io#65]
コメント失礼します。記事をいつも反復させて頂いております。

インデックス商品について下記の条件を示されていますが、コストが安く時価総額加重平均であればナスダック100や新興国のインデックス商品も投資対象として問題ないというお考えでしょうか？
・コスト（信託報酬）の安い
・時価総額加重平均を採用したインデックスファンド （S&P500、全米、全世界など）

お手数おかけしますがご確認よろしくお願いします

**Comment by hayatoito** [comment]
質問ありがとうございます。

[インデックスファンドとしては、アメリカ株 (S&P500 や VTI）100%でよいのでしょうか？ それとも、オルカン のように全世界株のほうがよいのでしょうか？](https://hayatoito.github.io/2020/investing/#s-p500-vti-100)
を参考にしてください。
