### ISSUE TITLE
Question on currency risk

### ISSUE THREAD

**Issue by wineSumida** [hayatoito/hayatoito.github.io#70]
初めまして。
昨年末こちらのサイトを拝見し、大変勉強させて頂きました。
本年から新NISAの積立を始めております。

ご提示下さっている内容は基本的にどれも得心のいくもの、かつこれまでしっかりと理解できていなかった視点もあり、誠に感銘を受けております。
とくに最初に強調なさっている「アセットアロケーション」については充分考えることが無かった、つまり新NISAは最大1800万円の枠があるから、当然1800万円フルに投資するものだという漫然とした思い込みがあったのですが、そこを正して頂けたりしています。

さて、記事中でも為替リスクについての言及をしておいでです。
結論としては必要以上に恐れるな、ということでしたが、現在のところ大変円安が進んでいます。
昨年一年間で20円近く動いていて、やはり気になるところではあります。
ネットを見ても「為替リスクには要注意」といったような言説を目にすることも少なくなく、要注意といわれてもな……と途方に暮れたりします。

記事では為替リスクは10％という仮定でお書きになっておいででしたが、今現在の水準を考慮したとき、どのような考え方・捉え方でこの為替リスクと向き合うべきでしょうか？
なんとなく、オルカン一本では無く、年明けから調子が良いこともあるし日本株のインデックスも取り入れるか……みたいなことも思ったりしてしまうのですが、これも「余計なこと」になりますでしょうか。

もし宜しければ、ご見解の追記をご検討頂けますと幸甚です。
何卒よろしくお願いいたします。

wineSumida

**Comment by hayatoito** [comment]
為替リスクとの向き合い方については、書籍のほうに、詳しくコラムを書きました。

- [Amazon: 普通の人が資産運用で99点をとる方法とその考え方](https://www.amazon.co.jp/dp/4296001825)

しばらくの間は、書籍のほうを参考にしてください。
