### ISSUE TITLE
Typo: create_root

### ISSUE THREAD

**Issue by simon-i1-h** [hayatoito/hayatoito.github.io#8]
create_root → crate_root
<https://github.com/hayatoito/hayatoito.github.io/blob/a94eb7f30c1c6b14537c43e11c419bed0d6048d5/2017/faq/index.html#L627>
<https://github.com/hayatoito/hayatoito.github.io/blob/a94eb7f30c1c6b14537c43e11c419bed0d6048d5/feeds/all.atom.xml#L560>
<https://github.com/hayatoito/hayatoito.github.io/blob/a94eb7f30c1c6b14537c43e11c419bed0d6048d5/feeds/hayato-ito.atom.xml#L560>

**Comment by hayatoito** [comment]
Thanks. Fixed.
