### ISSUE TITLE
書籍　質問

### ISSUE THREAD

**Issue by jiro-123** [hayatoito/hayatoito.github.io#80]
書籍化おめでとうございます。

本書の巻末付録付録①P139の特定口座の税金の計算式(URL先のRustの計算式も同様)について質問ですが、

let 税金 = 評価額 * 税率;

となっておりますが、

let 税金 = (評価額 - 投資額 * (1.0 - 所得税率)) * 税率;

の方がより正確なのかなと思いましたが、いかがでしょうか？

**Comment by hayatoito** [comment]
ありがとうございます！確認しました。指摘が正しいです。
issue  #78 に修正内容を載せました。ご確認ください。

**Comment by jiro-123** [comment]
確認しました。修正ありがとうございます！
