### ISSUE TITLE
長期投資での標準偏差について

### ISSUE THREAD

**Issue by PrestConFuoco** [hayatoito/hayatoito.github.io#81]
書籍を読んでこちらに来ました。素晴らしい情報を有難うございます。
さて、[長期投資ではリスクは減るってききました？本当ですか？]に、「「商品を n 年間保有するとして、その n 年間における成績のブレ・標準偏差」 を  とした場合、これは√n σ になります。」とあります。
これは単利の場合で、n年間保有の場合は複利になり標準偏差はもっと大きくなるのではないでしょうか。
1年目に例えば1.1倍になった場合は2年目の標準偏差は1.1σになるとのではないかと思いますが、いかがでしょうか。
また、このあたりで参考とされた情報などありましたら教えていただけると幸いです。

**Comment by hayatoito** [comment]
>  これは単利の場合で、n年間保有の場合は複利になり標準偏差はもっと大きくなるのではないでしょうか。 1年目に例えば1.1倍になった場合は2年目の標準偏差は1.1σになるとのではないかと思いますが、いかがでしょうか。

ならないです。評価額が複利であることは、その標準偏差が"複利"であることを意味しません。

標準偏差が指数関数的に増加するには、相当ありえない仮定をする必要がありますね。
例えば以下のような通常ありえない確率過程のときです。

- 1年目にリターンが10%だった場合、 2年目以降のリターンは毎年*確実*に10%になる
- 1年目にリターンが-5%だった場合、 2年目以降のリターンは毎年*確実*に-5%になる
- ...

もちろん、幾何ブラウン運動ではそのような仮定はしません。1年目にリターンが10%だったからといって、2年目以降のリターンには影響しません。


> また、このあたりで参考とされた情報などありましたら教えていただけると幸いです。

"Square Root of Time Rule"  あるいは "リスクの√Ｔ倍ルール"等のキーワードで検索するとよいと思います。

**Comment by PrestConFuoco** [comment]
丁寧な回答ありがとうございます。また、キーワードも非常に有用でした。
