### ISSUE TITLE
[Typo] もどついた should be もとづいた

### ISSUE THREAD

**Issue by peria** [hayatoito/hayatoito.github.io#9]
[The 24th post of Chromium Advent Calendar](https://hayato.io/2017/dom/)  has a wrong word "もどついた" in between 課題9 and 課題10.

> この記事はほぼ静的ページです。最初に記事が読み込まれた後はツリーの構造は一部を除いて変化しません。 それに対して多くの Web ページの内容は動的に更新されます。つまりブラウザ内部で保持しているノードツリーの構造は常にアップデートされています。 そのためツリーに関する情報もなんらかのタイミングでアップデートする必要があります。ユーザーに古い情報に **もどついた** 間違った結果を返すことは許されません。

It should be "もとづいた" or "基づいた".

**Comment by hayatoito** [comment]
Thanks! Fixed.
